### PR TITLE
adding support for Claude, Replicate, Cohere, Azure

### PR DESCRIPTION
**Pull request by ghost**
Hi @sunnweiwei,

Following up on my issue - https://github.com/sunnweiwei/RankGPT/issues/6. I'm working on litellm (simple library to standardize LLM API Calls - https://github.com/BerriAI/litellm) and was wondering if we could be helpful.

Added support for Anthropic, Llama2, and Cohere by adding an `if` condition to your `chat` function. The code is pretty similar to the OpenAI class - as litellm follows the same pattern as the openai-python sdk.

Would love to know if this helps.

### CODE REVIEW

**Comment by sunnweiwei** [comment]
Merged. Thanks for your great work :D

**Comment by ghost** [comment]
Thanks @sunnweiwei the README looks the same? What do you think is the best way of communicating how users can use other llm providers?

**Comment by sunnweiwei** [comment]
I've added the update to `News` section and fixed the inconsistency caused by renaming the `api_key`.

**Comment by austinmw** [comment]
@krrishdholakia Hi, curious if this could be extended to additionally support Claude through Amazon Bedrock?

**Pull request merged**
